---
title: "Simple Linear Regression Inference"
output: pdf_document
---

```{r}
library(tidyverse)
library(faraway)
library(broom)
```

## SLR Example

Is there a linear relationship between length of stay and number of beds?

```{r}
# load data
data_hosp = read_csv("./R - Module 17/Hospital.csv")

# plot relationship
data_hosp %>% ggplot() + 
  geom_point(aes(x = BEDS, y = LOS)) + 
  theme_bw() + 
  labs(x = "Number of beds", y = "Length of stay (days)")

# fit model
reg_hos = lm(LOS ~ BEDS, data = data_hosp)
summary(reg_hos)

# anova table
anova(reg_hos)

# extract esidual st error: MSE = sigma^2
glance(reg_hos)$sigma

# Scatter plot with regression line overlaid  
data_hosp %>% 
  ggplot(aes(BEDS, LOS)) + geom_point(color='blue') + 
  theme_bw() +
  geom_smooth(method='lm', se=FALSE, color='red') +
  labs(x="Number of beds", y="Length of stay (days)")

# Scatter plot with regression line overlaid and 95% confidence bands
data_hosp %>% 
  ggplot(aes(BEDS, LOS)) + geom_point(color='blue') + 
  theme_bw() +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="Number of beds", y="Length of stay (days)")

# CIs for both slope and intercept
confint(reg_hos)
confint(reg_hos,level = 0.90)

# find 95% CI for 100 beds difference
res = tidy(reg_hos) %>% filter(term == "BEDS")
estimate = res$estimate
std.error = res$std.error
cv = qt(0.975, df = 113 - 2)

lower = 100*estimate - 100*std.error*cv
upper = 100*estimate + 100*std.error*cv

c(lower, upper)

```

## Prediction Intervals

```{r}
# 95% confidence interval using predict()
predict.lm(reg_hos, interval = "confidence") 

# 95% prediction interval 
predict.lm(reg_hos, interval = "prediction") 

# Calculate a 95% prediction interval for X = 200 and X = 600 beds
new.hosp = data.frame(BEDS = c(200,600))
predict(reg_hos, newdata = new.hosp, interval="prediction", level=0.95)

# Calculate a 95% confidence interval for X=200 and X=600 BEDS
predict(reg_hos, newdata = new.hosp, interval="confidence", level=0.95)

```
## Correlation Coefficient and R-squared

```{r}
# R-squared = Correlation^2 only in SLR
glance(reg_hos)$r.squared
cor(data_hosp$LOS, data_hosp$BEDS)^2

```



