---
title: "Model Building and Variable Selection"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(corrplot)
library(leaps)

```

## Exploratory Analysis

```{r}
# read data 
surg = read_csv("./Surgical.csv") %>% dplyr::select(-Survival)

# exploratory
pairs(surg)

# correlation plot
corrplot(cor(surg), type = "upper", diag = FALSE)

# Boxplots for each variable
par(mfrow=c(2,3))
boxplot(surg$Lnsurvival, main='Lnsurvival')
boxplot(surg$Age, main='Age')
boxplot(surg$Bloodclot,main='Bloodclot' )
boxplot(surg$Progindex, main='Progindex')
boxplot(surg$Enzyme, main='Enzyme')
boxplot(surg$Liver, main='Liver')

# fit regression using all predictors
mult.fit = lm(Lnsurvival ~ ., data = surg)
summary(mult.fit)

```

## Backwards Elimination

Take out non-significant variables one at a time starting with the highest p-value.

```{r}
# No Liver
step1 = update(mult.fit, . ~ . -Liver)
summary(step1)

# No Alcmod
step2 = update(step1, . ~ . -Alcmod)
summary(step2)

# No Age
step3 = update(step2, . ~ . -Age)
summary(step3)

# No Gender
step4 = update(step3, . ~ . -Gender)
summary(step4)

# just use one function
step(mult.fit, direction='backward')
step
```

## Forward Selection

Reversed backward elimination starting with the lowest p-value.

```{r}
### Step 1:  Fit simple linear regressions for all variables,look for the variable with lowest p-value
fit1 = lm(Lnsurvival ~ Bloodclot, data = surg)
summary(fit1)
fit2 = lm(Lnsurvival ~ Progindex, data = surg)
summary(fit2)
fit3 = lm(Lnsurvival ~ Enzyme, data = surg)
summary(fit3)
fit4 = lm(Lnsurvival ~ Liver, data = surg)
summary(fit4)
fit5 = lm(Lnsurvival ~ Age, data = surg)
summary(fit5)
fit6 = lm(Lnsurvival ~ Gender, data = surg)
summary(fit6)
fit7 = lm(Lnsurvival ~ Alcmod, data = surg)
summary(fit7)
fit8 = lm(Lnsurvival ~ Alcheav, data = surg)
summary(fit8)

# Enter first the one with the lowest p-value: Enzyme
forward1 = lm(Lnsurvival ~ Enzyme, data = surg)
summary(forward1)

### Step 2: Enter the one with the lowest p-value in the rest 
fit1 = update(forward1, . ~ . +Bloodclot)
summary(fit1)
fit2 = update(forward1, . ~ . +Progindex)
summary(fit2)
fit3 = update(forward1, . ~ . +Liver)
summary(fit3)
fit4 = update(forward1, . ~ . +Age)
summary(fit4)
fit5 = update(forward1, . ~ . +Gender)
summary(fit5)
fit6 = update(forward1, . ~ . +Alcmod)
summary(fit6)
fit7 = update(forward1, . ~ . +Alcheav)
summary(fit7)

# Enter the one with the lowest p-value: Progindex
forward2 = update(forward1, . ~ . + Progindex)
summary(forward2)

### Step 3: Enter the one with the lowest p-value in the rest 
fit1 = update(forward2, . ~ . +Bloodclot)
summary(fit1)
fit2 = update(forward2, . ~ . +Liver)
summary(fit2)
fit3 = update(forward2, . ~ . +Age)
summary(fit3)
fit4 = update(forward2, . ~ . +Gender)
summary(fit4)
fit5 = update(forward2, . ~ . +Alcmod)
summary(fit5)
fit6 = update(forward2, . ~ . +Alcheav)
summary(fit6)
# Enter the one with the lowest p-value: Alcheav
forward3 = update(forward2, . ~ . + Alcheav)
summary(forward3)

### Step 4: Enter the one with the lowest p-value in the rest 
fit1 = update(forward3, . ~ . +Bloodclot)
summary(fit1)
fit2 = update(forward3, . ~ . +Liver)
summary(fit2)
fit3 = update(forward3, . ~ . +Age)
summary(fit3)
fit4 = update(forward3, . ~ . +Gender)
summary(fit4)
fit5 = update(forward3, . ~ . +Alcmod)
summary(fit5)
# Enter the one with the lowest p-value: Bloodclot
forward4 = update(forward3, . ~ . + Bloodclot)
summary(forward4)


### Step 5: Enter the one with the lowest p-value in the rest 
fit1 = update(forward4, . ~ . +Liver)
summary(fit1)
fit2 = update(forward4, . ~ . +Age)
summary(fit2)
fit3 = update(forward4, . ~ . +Gender)
summary(fit3)
fit4 = update(forward4, . ~ . +Alcmod)
summary(fit4)
# P-value of all new added variables are larger than 0.05, which means that they 
# are not significant predictor, and we stop here.

# The model we obtained is Lnsurvival ~ Enzyme + Progindex + Alcheav + Bloodclot
mult.fit.final = lm(Lnsurvival ~ Enzyme + Progindex + Alcheav + Bloodclot, data = surg)
summary(mult.fit.final)

# fit using one function
step(mult.fit, direction = 'forward')

```

## Test Based Procedures

```{r}
mat = as.matrix(surg)
# Printing the 2 best models of each size, using the Cp criterion:
leaps(x = mat[,1:8], y = mat[,9], nbest = 2, method = "Cp")

# Printing the 2 best models of each size, using the adjusted R^2 criterion:
leaps(x = mat[,1:8], y = mat[,9], nbest = 2, method = "adjr2")

# Function regsubsets() performs a subset selection by identifying the "best" model that contains
# a certain number of predictors. By default "best" is chosen using SSE/RSS (smaller is better)
b = regsubsets(Lnsurvival ~ ., data = surg)
rs = summary(b)

# plot of Cp and Adj-R2 as functions of parameters
par(mfrow=c(1,2))

plot(2:9, rs$cp, xlab="No of parameters", ylab="Cp Statistic")
abline(0,1)

plot(2:9, rs$adjr2, xlab="No of parameters", ylab="Adj R2")

```



