---
title: "Multiple Linear Regression"
output: pdf_document
---

```{r}
library(tidyverse)
library(faraway)
library(broom)
```

## MLR Example

```{r}
# read data
data_hosp = read_csv("./R - Module 18/Hospital.csv")

# Scatter plot with regression line overlaid and 95% confidence bands
data_hosp %>% 
  ggplot(aes(BEDS, LOS)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="Number of beds", y="Length of stay (days)")

# Simple linear regression: Length of stay (LOS) vs number of BEDS 
reg_hos = lm(LOS ~ BEDS, data = data_hosp)
summary(reg_hos)

# Get the ANOVA table
anova(reg_hos)

# MLR LOS vs BEDS + INFRISK
regmult1_hos = lm(LOS ~ BEDS + INFRISK, data = data_hosp)
summary(regmult1_hos)

# MLR LOS vs BEDS + INFRISK + NURSE
regmulti2_hos = lm(LOS ~ BEDS + INFRISK + NURSE, data = data_hosp)
summary(regmulti2_hos)

```

Is there a relationship between length of stay, number of beds, and medical school affiliation?

```{r}
# Recode MEDSCHL: Yes:1 and No:0
data_hosp = mutate(data_hosp, MEDSCHL = ifelse(MEDSCHL == 1, 1, 0))

# MLR
regmult2_hos = lm(LOS ~ INFRISK + MEDSCHL, data = data_hosp)
summary(regmult2_hos)

```

Is there a relationship between length of stay, risk and medical school affiliation?

```{r}
# fit MLR
regmult3_hos = lm(LOS ~ INFRISK + MEDSCHL, data = data_hosp)
summary(regmult3_hos)

```


What if we use the categorical predictor REGION (1:NE, 2:NC, 3:S, 4:W)?

```{r}
# fit model without factoring - wrong
cat1 = lm(LOS ~ REGION, data = data_hosp)
summary(cat1)

# fit model with factoring 
cat2 = lm(LOS ~ factor(REGION), data = data_hosp)
summary(cat2)

# no intercept model
cat3 = lm(LOS ~ 0 + factor(REGION), data = data_hosp)
summary(cat3)

# change regerence from 1 to 3
data_hosp = mutate(data_hosp, REGION = relevel(factor(REGION), ref = 3))
cat4 = lm(LOS ~ REGION, data = data_hosp)
summary(cat4)

```

```{r}
# MLR
regmulti4_hos = lm(LOS ~ INFRISK + MEDSCHL + factor(REGION), data = data_hosp)
summary(regmulti4_hos)

# 'General' global test for all predictors
anova(regmult4_hos)

# MLR with interaction
regmult5_hos = lm(LOS ~ INFRISK*MEDSCHL, data = data_hosp)
summary(regmult5_hos)

# Vizualize interaction for reg5: LOS vs INFRISK by MS affiliation
qplot(x = INFRISK, y = LOS, color = factor(MEDSCHL), data = data_hosp) +
  geom_smooth(method = "lm", se=FALSE) +
  theme_bw() +
  labs(x="Infection Risk", y="Length of stay (days)", color = "Med School") 

# Lines look fairly parallel, in line with the non-sig interaction result.


```





